// leetcode:-389. Find the Difference.

// Que 2 :- You are given two strings s and t. 
          //String t is generated by random shuffling string s and then add one more letter at a random position.
          //Return the letter that was added to t.
package String;
public class string7 {
    public static void main(String[] args) {
        String s = "abcd";
        String t = "abcde";
        System.out.println(difference(s, t));
    }

    public static char difference(String s, String t){
        char result = 0;

        for(int i = 0; i<s.length(); i++){
            result ^= s.charAt(i);
        }

        for(int j = 0; j<t.length(); j++){
            result ^= t.charAt(j);
        }
        return result;
    }
}

// Output: e